In [1]:
#numpy
import numpy as np

#ndim()-Displays the dimensin of array
a=np.array([[1,2,3],[6,7,9],[54,2,5]])
print(np.ndim(a))

#shape()-Displays No.of rows and coloums in array
print(np.shape(a))

#size()-Display number of elements in the array
print(np.size(a))

#dtype()-Displays the data type
print(a.dtype)

print(type(a))

2
(3, 3)
9
int32
<class 'numpy.ndarray'>


In [12]:
z=np.zeros([3,3],int)
print(z)
o=np.ones([4,4],int)
print(o)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [3]:
#1-d array
b=np.array([1,2,3,4,5,6,7])
#2-d array
c=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(c)
print("\n-----------------------------------")
#slicing
print(b[0:8:2])
print(b[::2])
print("\n----------------------------------")

[1 2 3 4 5 6 7]
[[1 2 3 4]
 [5 6 7 8]]

-----------------------------------
[1 3 5 7]
[1 3 5 7]

----------------------------------


In [4]:
#Basic functions
#where()-replaces or processes the elements of numpy array which satisfies the condition
d=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.where(d%2==0,"even","odd"))#[where(condition,if true this will print,else this will print)]

#Dataframing
import pandas as pd
data=pd.DataFrame({"Name":["Mani","Rani","Reddy","Shyam"],"Age":[21,14,17,32]}) #data framing from pandas
print("Before checking\n",data)
data["Eligibility"]=np.where(data["Age"]>=18,"Eligible","Not Eligible")
print("After checking:\n",data)

['odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even']
Before checking
     Name  Age
0   Mani   21
1   Rani   14
2  Reddy   17
3  Shyam   32
After checking:
     Name  Age   Eligibility
0   Mani   21      Eligible
1   Rani   14  Not Eligible
2  Reddy   17  Not Eligible
3  Shyam   32      Eligible


In [5]:
#Functions of Rounding
e=np.array([11.033,3.808,54.1234,333.123489])
print("input Array:",e)

print("\nAfter rounding:")
print(np.around(e,2,))  #around(arrayName,No.of decimals )
print(np.around(e,decimals=-1))

input Array: [ 11.033      3.808     54.1234   333.123489]

After rounding:
[ 11.03   3.81  54.12 333.12]
[ 10.   0.  50. 330.]


In [6]:
#floor()-returns floor value of a decimal
f=[1.22,33.66,7,8.95,0.9876]
f1=np.floor(f)
print(f1)

#ceil()-returns higher round figure 
f2=np.ceil(f)
print(f2)

[ 1. 33.  7.  8.  0.]
[ 2. 34.  7.  9.  1.]


In [7]:
#Statistical functions
g=np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(g))
print(np.mean(g))
print("---------------------------------------")
print(np.median(g)) 
g2=np.array([[1,2,3,4,5],[6,7,9,65,33],[54,2,5,7,22]])
print(np.std(g))    #Standard deviation
# for 2 d arrays
print(np.median(g2,axis=0))  #for each nth element each sub-array
print(np.median(g2,axis=1))   #for different sub-arrays


45
5.0
---------------------------------------
5.0
2.581988897471611
[ 6.  2.  5.  7. 22.]
[3. 9. 7.]


In [17]:
#arange()
#reshape()
#creating matrix using numpy
matrix=np.arange(1,10).reshape((3,3))
print(matrix)
print(np.shape(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [26]:
#take()
print(matrix.take(6))
print(matrix.take(0,axis=1))
print(matrix.take(0,axis=0))
print(matrix.take(1,axis=1))

7
[1 4 7]
[1 2 3]
[2 5 8]


In [28]:
#trace()-prints sum of diagonal elements
#diagonal()-prints diagonal elements
print(np.trace(matrix))
print(np.diagonal(matrix))

15
[1 5 9]


In [46]:
#matrix add,sub,mult
matrix1=np.arange(10,19).reshape(3,3)
print(matrix1)
print("-------------------------")
print(np.add(matrix,matrix1))
print("-------------------------")
print(np.subtract(matrix,matrix1))
print("-------------------------")
print(np.dot(matrix,matrix1))

[[10 11 12]
 [13 14 15]
 [16 17 18]]
-------------------------
[[11 13 15]
 [17 19 21]
 [23 25 27]]
-------------------------
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
-------------------------
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [47]:
#Addding rows/columns to an array
#using column_stack()
m1=np.arange(1,10).reshape(3,3)
print(m1)
print("-----------------------------------")
add=np.array([0,0,0])
result=np.column_stack((m1,add))
print(result)
print("=----------------------------------")
#using vstack()
print(np.vstack((m1,add)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------------------------
[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
=----------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]


In [48]:
#adding new rows to empty array 
#append()
empty=np.empty((0,3),int)  #3-Darray
print(empty)
print("-------------------")
empty=np.append(empty,np.array([[1,5,9]]),axis=0)
empty=np.append(empty,np.array([[5,1,9]]),axis=0)
empty=np.append(empty,np.array([[9,5,1]]),axis=0)
print(empty)

[]
-------------------
[[1 5 9]
 [5 1 9]
 [9 5 1]]


In [56]:
#finding eigen value of matrix
#eigvals()
from numpy import linalg as LA
eigen=LA.eigvals([[1,2],[3,4]])
e3=np.linalg.eigvals([[1,2],[3,4]])
print(eigen)
print(e3)
print("---------------------------------")
#finding determinant
print(np.linalg.det([[1,2],[3,4]]))
print(LA.det([[1,2],[3,4]]))

[-0.37228132  5.37228132]
[-0.37228132  5.37228132]
---------------------------------
-2.0000000000000004
-2.0000000000000004


In [58]:
# Python program to inverse
A = np.array([[6, 1, 1],
			[4, -2, 5],
			[2, 8, 7]])
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [64]:
#calculating frequency of each element in an array
#unique()
fre=np.array([1,2,3,4,5,3,2,2,6,7,8,5,5,5])
unique,frequency=np.unique(fre,return_counts=True)

result=np.array((unique,frequency)).T
print(result)

[[1 1]
 [2 3]
 [3 2]
 [4 1]
 [5 4]
 [6 1]
 [7 1]
 [8 1]]


In [65]:
#multiplying Complex number matrix
#vdot()
c1=np.array([[2+3j,4+5j],[4+5j,6+7j]])
c2=np.array([[2+2j,2+9j],[1+5j,4+3j]])
complex=np.vdot(c1,c2)
print(complex)

(137+29j)


In [67]:
#finding outer,inner,crossProduct of two vectors/Matrix
#outer(),inner(),cross()
matrix1 = np.array([[1, 3], [2, 6]])
matrix2 = np.array([[0, 1], [1, 9]])
print(np.outer(matrix1,matrix2))
print("-----------------------")
print(np.inner(matrix1,matrix2))
print("-----------------------")
print(np.cross(matrix1,matrix2))

[[ 0  1  1  9]
 [ 0  3  3 27]
 [ 0  2  2 18]
 [ 0  6  6 54]]
-----------------------
[[ 3 28]
 [ 6 56]]
-----------------------
[ 1 12]


In [70]:
#Covarience matrix of arrays
#cov()
print(np.cov(matrix1,matrix2))

[[ 2.   4.   1.   8. ]
 [ 4.   8.   2.  16. ]
 [ 1.   2.   0.5  4. ]
 [ 8.  16.   4.  32. ]] <class 'int'>


In [78]:
#Converting matrix to list
#tolist()
matrix1 = np.matrix('[1,2,3 ; 4,5,6 ; 6 ,7,8]')
list=matrix1.tolist()
print(matrix1)
print("-------------------------")
print(list)

AttributeError: 'list' object has no attribute 'T'